name: complimentary_colors
version: 1.0.3
description: An easy to use Dart package for calculating complimentary colors.
homepage: https://github.com/MegaMattMiller/complimentary_colors

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  color: ^3.0.0

dev_dependencies:
  test: ^1.11.1
  pedantic: ^1.9.0
